#!/bin/bash



IFS=$'\n'

declare -a arr

arr=( $(ls -A1 /dev/disk/by-label))

#echo "${#arr[@]}"

for i in "${arr[@]}"
do
  if [[ $i = cold* ]]
  then
    echo "Found: $i"
    tmp=${i#"cold"}
    if [ ! -d "/backups/$i" ]
    then
      echo "Launching backup of $tmp to $i"
      
      /projects/bash/backupDisk $i &> /sharedfolders/pool/Other/logs/$i.log &
    fi
  fi 
done
